export const demoContractorsForApproval = [
  {
    id: "sarah-1",
    name: "Sarah Chen",
    initials: "SC",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
  {
    id: "mike-2",
    name: "Mike Johnson",
    initials: "MJ",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
  {
    id: "emma-3",
    name: "Emma Davis",
    initials: "ED",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
  {
    id: "tom-4",
    name: "Tom Martinez",
    initials: "TM",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
  {
    id: "lisa-5",
    name: "Lisa Park",
    initials: "LP",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
  {
    id: "james-6",
    name: "James Wilson",
    initials: "JW",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
  {
    id: "alex-7",
    name: "Alex Kim",
    initials: "AK",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
  {
    id: "jordan-8",
    name: "Jordan Lee",
    initials: "JL",
    role: "Developer",
    defaultHours: "8h/day",
    thisMonth: {
      total: 38.5,
      approved: 24,
      pending: 14.5,
    },
    status: "pending" as const,
  },
];
