/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gcdtimasyknakdojiufl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZHRpbWFzeWtuYWtkb2ppdWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2Mjk2MjksImV4cCI6MjA3NjIwNTYyOX0.uEeE-mYaV6L00Ta_-KNbz96XghmD30M90luptRJaxAM"